import test from 'node:test';
import assert from 'node:assert/strict';
import { activateRoom, createRoom, joinRoom, roomStore, setGameMode, setPlayerReady, startRoom } from '../rooms.js';
import { advanceTurnIfDue9, fireProjectile9, phase9TestHooks, publicRoomState9 } from '../phase9.js';

function started(){roomStore.clear();const room=createRoom('a','A').room;assert.equal(joinRoom(room.code,'b','B').ok,true);assert.equal(setGameMode('a','survival').ok,true);assert.equal(setPlayerReady('a',true).ok,true);assert.equal(setPlayerReady('b',true).ok,true);assert.equal(startRoom('a').ok,true);activateRoom(room.code,room.match.startAt);return room;}

test('v0.9 pickup frenzy starts at turn 10, spawns at most once per turn, and never exceeds four live boxes',()=>{const room=started();room.pickups=[];room.match.turnNumber=10;room.phase9PickupAttemptTurn=0;assert.equal(phase9TestHooks.maintainPhase9Pickups(room),true);assert.equal(room.pickups.length,1);assert.equal(room.pickups[0].spawnTurn,10);assert.equal(phase9TestHooks.maintainPhase9Pickups(room),false);for(let turn=11;turn<=20;turn+=1){room.match.turnNumber=turn;phase9TestHooks.maintainPhase9Pickups(room);assert.ok(room.pickups.length<=4);assert.equal(phase9TestHooks.maintainPhase9Pickups(room),false);}assert.ok(room.pickups.length>0);assert.ok(room.pickups.every(box=>room.match.turnNumber<=box.expiresAfterTurn));});

test('v0.9.2 first pickup is centered between two living players',()=>{const room=started();room.pickups=[];room.players[0].spawn={x:1000,y:3000};room.players[1].spawn={x:3000,y:3000};room.match.turnNumber=10;assert.equal(phase9TestHooks.spawnPhase9Pickup(room),true);assert.equal(room.pickups.length,1);assert.ok(Math.abs(room.pickups[0].x-2000)<=1);});

test('v0.9.2 also repositions an early historical pickup to the fair midpoint',()=>{const room=started();room.players[0].spawn={x:1000,y:3000};room.players[1].spawn={x:3000,y:3000};room.match.turnNumber=3;room.pickups=[{id:'early',type:'heavy',label:'HEAVY BOMB',x:4200,y:2500,spawnTurn:3,expiresAfterTurn:6}];assert.equal(phase9TestHooks.maintainPhase9Pickups(room),true);assert.ok(Math.abs(room.pickups[0].x-2000)<=1);assert.equal(room.pickups[0].phase9FairPlaced,true);});

test('v0.9.2 distributes midpoint candidates across adjacent player gaps before stacking one gap',()=>{const room=started();room.players.push({id:'c',name:'C',alive:true,spawn:{x:4000,y:3000},inventory:[null,null],pickupCollectedTurn:-1});room.players[0].spawn={x:800,y:3000};room.players[1].spawn={x:2400,y:3000};room.pickups=[];for(let i=0;i<2;i+=1){room.match.turnNumber=10+i;assert.equal(phase9TestHooks.spawnPhase9Pickup(room),true);}const xs=room.pickups.map(box=>box.x).sort((a,b)=>a-b);assert.ok(Math.abs(xs[0]-1600)<=1);assert.ok(Math.abs(xs[1]-3200)<=1);});

test('legacy Heal +30 labels are normalized to Heal +20 in boxes and inventory',()=>{const room=started(),player=room.players[0];room.pickups=[{id:'heal-old',type:'heal',label:'HEAL +30',x:2000,y:2500,spawnTurn:1,expiresAfterTurn:99}];player.inventory=[{type:'heal',label:'HEAL +30'},null];phase9TestHooks.ensurePhase9(room);assert.equal(room.pickups[0].label,'HEAL +20');assert.equal(player.inventory[0].label,'HEAL +20');const state=publicRoomState9(room);assert.equal(state.itemPool.find(item=>item.type==='heal').label,'HEAL +20');});

test('a player can collect only one pickup per turn even when two boxes overlap',()=>{const room=started(),player=room.players.find(p=>p.id===room.match.activePlayerId);room.match.turnNumber=10;player.inventory=[null,null];player.pickupCollectedTurn=-1;room.pickups=[{id:'one',type:'heavy',label:'HEAVY BOMB',x:player.spawn.x,y:player.spawn.y-8,spawnTurn:10,expiresAfterTurn:13},{id:'two',type:'triple',label:'TRIPLE SHOT',x:player.spawn.x,y:player.spawn.y-8,spawnTurn:10,expiresAfterTurn:13}];assert.equal(phase9TestHooks.collectOneByTouch(room,player),true);assert.equal(player.inventory.filter(Boolean).length,1);assert.equal(room.pickups.length,1);assert.equal(phase9TestHooks.collectOneByTouch(room,player),false);room.match.turnNumber=11;assert.equal(phase9TestHooks.collectOneByTouch(room,player),true);assert.equal(player.inventory.filter(Boolean).length,2);assert.equal(room.pickups.length,0);});

test('v0.9.6 pickup collection triggers when the vehicle hitbox only grazes the pickup visual',()=>{const room=started(),player=room.players.find(p=>p.id===room.match.activePlayerId);room.match.turnNumber=10;player.inventory=[null,null];player.pickupCollectedTurn=-1;const oldRadius=64;assert.ok(phase9TestHooks.PICKUP_TOUCH_RADIUS>oldRadius);room.pickups=[{id:'edge-touch',type:'heavy',label:'HEAVY BOMB',x:player.spawn.x+phase9TestHooks.PICKUP_TOUCH_RADIUS-1,y:player.spawn.y-8,spawnTurn:10,expiresAfterTurn:13}];assert.equal(phase9TestHooks.collectOneByTouch(room,player),true);assert.equal(player.inventory[0]?.type,'heavy');assert.equal(room.pickups.length,0);});

test('a projectile explosion cannot collect a pickup in v0.9',()=>{const room=started(),shooterId=room.match.activePlayerId,shooter=room.players.find(p=>p.id===shooterId);shooter.inventory=[null,null];shooter.selectedItemSlot=1;const fired=fireProjectile9(shooterId);assert.equal(fired.ok,true);const q=room.match.projectile;room.pickups=[{id:'blast-box',type:'heavy',label:'HEAVY BOMB',x:q.impactX,y:q.impactY,spawnTurn:room.match.turnNumber,expiresAfterTurn:room.match.turnNumber+3}];const changed=advanceTurnIfDue9(room.code,q.resolveAt+1);assert.ok(changed);assert.equal(shooter.inventory.filter(Boolean).length,0);assert.equal(room.pickups.some(box=>box.id==='blast-box'),true);});

test('public v0.9.8 release candidate state advertises frenzy pacing, fair midpoint placement and touch-only edge collection',()=>{const room=started(),state=publicRoomState9(room);assert.equal(state.version,'0.9.8-release-candidate');assert.equal(state.phase,'9');assert.equal(state.pickupRules.earlyEveryTurns,3);assert.equal(state.pickupRules.frenzyStartsAtTurn,10);assert.equal(state.pickupRules.frenzyEveryTurns,1);assert.equal(state.pickupRules.maxOnMap,4);assert.equal(state.pickupRules.maxCollectedPerPlayerTurn,1);assert.equal(state.pickupRules.collectByTouch,true);assert.equal(state.pickupRules.collectByExplosion,false);assert.equal(state.pickupRules.pickupEndsTurn,false);assert.equal(state.pickupRules.touchRadius,phase9TestHooks.PICKUP_TOUCH_RADIUS);assert.match(state.pickupRules.placement,/midpoints/i);});
