import test from 'node:test';
import assert from 'node:assert/strict';
import { activateRoom, createRoom, joinRoom, roomStore, setGameMode, setPlayerReady, startRoom } from '../rooms.js';
import { advanceTurnIfDue6DV09, fireProjectile6DV09, publicRoomState6DV09 } from '../phase6d-v09.js';

function started(){roomStore.clear();const room=createRoom('a','A').room;assert.equal(joinRoom(room.code,'b','B').ok,true);assert.equal(setGameMode('a','survival').ok,true);assert.equal(setPlayerReady('a',true).ok,true);assert.equal(setPlayerReady('b',true).ok,true);assert.equal(startRoom('a').ok,true);activateRoom(room.code,room.match.startAt);return room;}
function actors(room){const shooter=room.players.find(p=>p.id===room.match.activePlayerId),target=room.players.find(p=>p.id!==shooter.id);shooter.motion=null;target.motion=null;return{shooter,target};}
function equip(player,type,label){player.inventory=[{type,label},null];player.selectedItemSlot=2;}

test('v0.9.7 pre-release public combat contract exposes radial Cluster and Air Strike damage',()=>{const room=started(),b=publicRoomState6DV09(room).v09CombatBalance;assert.equal(b.version,'0.9.7-pre-release');assert.equal(b.maxHp,100);assert.equal(b.basicMaxDamage,10);assert.equal(b.heavyMaxDamage,20);assert.equal(b.tripleDamagePerDirectHit,10);assert.equal(b.clusterMainDirectHitDamage,10);assert.equal(b.clusterSubhitMaxDamage,5);assert.equal(b.clusterSubhitExplosionRadius,150);assert.equal(b.airStrikeMaxDamagePerShell,5);assert.equal(b.airStrikeExplosionRadius,165);assert.equal(b.nukeDamage,20);assert.equal(b.healAmount,20);assert.equal(b.shieldFactor,.5);assert.equal(b.vehicleHitRadius,51);});

test('Heal restores 20 HP with a hard cap of 100',()=>{const room=started(),{shooter}=actors(room);shooter.hp=55;equip(shooter,'heal','HEAL +20');const result=fireProjectile6DV09(shooter.id);assert.equal(result.ok,true);assert.equal(result.healed,20);assert.equal(shooter.hp,75);assert.equal(shooter.lastUtility.amount,20);});

test('Basic direct hit deals 10 instead of the historical 45',()=>{const room=started(),{shooter,target}=actors(room);target.hp=100;const result=fireProjectile6DV09(shooter.id);assert.equal(result.ok,true);const q=room.match.projectile,now=Date.now();q.impactReason='player';q.hitPlayerId=target.id;q.impactX=target.spawn.x;q.impactY=target.spawn.y-10;q.impactAt=now;q.resolveAt=now+900;q.resolutionApplied=false;room.match.turnEndsAt=q.resolveAt;advanceTurnIfDue6DV09(room.code,now);assert.equal(target.hp,90);assert.equal(target.lastDamage.amount,10);});

test('Heavy direct hit deals 20',()=>{const room=started(),{shooter,target}=actors(room);target.hp=100;equip(shooter,'heavy','HEAVY BOMB');const result=fireProjectile6DV09(shooter.id);assert.equal(result.ok,true);const q=room.match.projectile,now=Date.now();q.impactReason='player';q.hitPlayerId=target.id;q.impactX=target.spawn.x;q.impactY=target.spawn.y-10;q.impactAt=now;q.resolveAt=now+900;q.resolutionApplied=false;q.heavyResolutionApplied=false;room.match.turnEndsAt=q.resolveAt;advanceTurnIfDue6DV09(room.code,now);assert.equal(target.hp,80);assert.equal(target.lastDamage.amount,20);});

test('Triple counts only direct projectile hits and Shield protects the complete volley once',()=>{const room=started(),{shooter,target}=actors(room);target.hp=100;target.shield={factor:.5,activatedAt:Date.now(),activatedTurn:room.match.turnNumber};equip(shooter,'triple','TRIPLE SHOT');const result=fireProjectile6DV09(shooter.id);assert.equal(result.ok,true);const q=room.match.projectile,now=Date.now();q.impactAt=now-1;q.specialResolveAt=now;q.resolveAt=now+900;room.match.turnEndsAt=q.resolveAt;q.volley[0]={...q.volley[0],impactReason:'player',hitPlayerId:target.id,impactX:target.spawn.x,impactY:target.spawn.y-10,impactAt:now};q.volley[1]={...q.volley[1],impactReason:'terrain',hitPlayerId:null,impactX:target.spawn.x+400,impactY:target.spawn.y,impactAt:now};q.volley[2]={...q.volley[2],impactReason:'player',hitPlayerId:target.id,impactX:target.spawn.x,impactY:target.spawn.y-10,impactAt:now};advanceTurnIfDue6DV09(room.code,now);assert.equal(target.hp,90);assert.equal(target.lastDamage.amount,10);assert.equal(target.shield,null);});

test('Cluster main hit stays 10 and every subexplosion inside radius adds its own falloff damage',()=>{const room=started(),{shooter,target}=actors(room);target.hp=100;equip(shooter,'cluster','CLUSTER BOMB');const result=fireProjectile6DV09(shooter.id);assert.equal(result.ok,true);const q=room.match.projectile,now=Date.now();q.impactReason='player';q.hitPlayerId=target.id;q.impactX=target.spawn.x;q.impactY=target.spawn.y-10;q.impactAt=now-1;q.specialResolveAt=now;q.resolveAt=now+900;room.match.turnEndsAt=q.resolveAt;q.clusterImpacts=[{index:0,x:target.spawn.x,y:target.spawn.y-10,impactAt:now},{index:1,x:target.spawn.x+75,y:target.spawn.y-10,impactAt:now},{index:2,x:target.spawn.x+149,y:target.spawn.y-10,impactAt:now},{index:3,x:target.spawn.x+151,y:target.spawn.y-10,impactAt:now}];advanceTurnIfDue6DV09(room.code,now);assert.equal(target.hp,81);assert.equal(target.lastDamage.amount,19);});

test('Air Strike applies independent radial falloff damage for every shell whose explosion reaches the tank',()=>{const room=started(),{shooter,target}=actors(room);target.hp=100;equip(shooter,'airstrike','AIR STRIKE');const result=fireProjectile6DV09(shooter.id);assert.equal(result.ok,true);const q=room.match.projectile,now=Date.now();q.resolveAt=now+5000;room.match.turnEndsAt=q.resolveAt;for(const [index,shell] of q.airStrikeShells.entries()){shell.applied=false;shell.impactAt=index<4?now:now+3000+index*100;shell.y=target.spawn.y-10;if(index===0)shell.x=target.spawn.x;else if(index===1)shell.x=target.spawn.x+82;else if(index===2)shell.x=target.spawn.x+164;else if(index===3)shell.x=target.spawn.x+166;else shell.x=target.spawn.x+500;}advanceTurnIfDue6DV09(room.code,now);assert.equal(target.hp,91);assert.equal(target.lastDamage.amount,9);});
