import { randomInt } from 'node:crypto';
import { advanceTurnIfDue as baseAdvance, fireProjectile as baseFire, findRoomBySocket, jumpActivePlayer as baseJump, moveActivePlayer as baseMove, publicRoomState as basePublic } from './rooms.js';

const WORLD_WIDTH=5000,WORLD_HEIGHT=5000,GROUND_OFFSET=8,INVENTORY_SIZE=2,PICKUP_EVERY=3,PICKUP_LIFE=5,PICKUP_RADIUS=64,MAX_PICKUPS=2;
const HEAVY_DAMAGE=60,HEAVY_RADIUS=320,HEAVY_CRATER_RADIUS=190,HEAVY_CRATER_DEPTH=90;
const HOLES={rolling:[],terraces:[[2430,2550]],twinpeaks:[[2390,2510]],basin:[[1140,1240],[3760,3860]],brokenridge:[[1010,1140],[2410,2550],[3860,3980]],islands:[[900,1040],[1920,2080],[2910,3070],[3960,4110]],canyon:[[2380,2580]]};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const gaussian=(x,c,w,a)=>a*Math.exp(-((x-c)**2)/w);
const plateau=(x,l,r,y,f)=>x>=l&&x<=r?y:f;
function baseY(p,x){switch(p){case'terraces':{let y=3520+Math.sin(x/560)*100;y=plateau(x,330,900,3190,y);y=plateau(x,1040,1640,2920,y);y=plateau(x,1770,2350,3250,y);y=plateau(x,2630,3260,2820,y);y=plateau(x,3390,3970,3110,y);return plateau(x,4110,4680,2870,y);}case'twinpeaks':{let y=3650-gaussian(x,1200,260000,850)-gaussian(x,3820,300000,900)+Math.sin(x/280)*60;if(x>650&&x<980)y=3000;if(x>1510&&x<1850)y=3170;if(x>3150&&x<3460)y=3090;if(x>4050&&x<4410)y=2890;return y;}case'basin':{let y=2870+gaussian(x,2500,850000,690)+Math.sin(x/410)*65;if(x>420&&x<950)y=2750;if(x>1320&&x<1760)y=3160;if(x>3240&&x<3680)y=3160;if(x>4050&&x<4580)y=2750;return y;}case'brokenridge':{let y=3490+Math.sin(x/210)*170+Math.sin(x/690+1.1)*130;if(x>420&&x<900)y=3070;if(x>1260&&x<1720)y=2740;if(x>1900&&x<2320)y=3260;if(x>2700&&x<3160)y=2860;if(x>3330&&x<3770)y=3180;if(x>4140&&x<4620)y=2780;return y;}case'islands':if(x<900)return 3100-gaussian(x,520,90000,260);if(x<1920)return 2840-gaussian(x,1470,125000,190);if(x<2910)return 3260-gaussian(x,2480,130000,320);if(x<3960)return 2760-gaussian(x,3470,135000,220);return 3160-gaussian(x,4540,100000,280);case'canyon':{let y=2920+Math.min(Math.abs(x-2500)*.28,700);if(x>420&&x<980)y=2700;if(x>1120&&x<1640)y=3030;if(x>1800&&x<2260)y=3380;if(x>2740&&x<3200)y=3380;if(x>3360&&x<3880)y=3030;if(x>4020&&x<4580)y=2700;return y;}default:{let y=3440+Math.sin(x/470)*165+Math.sin(x/980+.7)*95;if(x>700&&x<1120)y=3140;if(x>1760&&x<2140)y=2920;if(x>2840&&x<3240)y=3170;if(x>3890&&x<4320)y=2860;return y;}}}
function surface(room,x){const px=clamp(x,0,WORLD_WIDTH),p=room.terrainPreset||'rolling';if((HOLES[p]||[]).some(([l,r])=>px>=l&&px<=r))return WORLD_HEIGHT;let y=baseY(p,px);for(const c of room.arena?.craters||[]){const dx=Math.abs(px-c.x);if(dx<c.radius)y+=c.depth*Math.sqrt(Math.max(0,1-(dx/c.radius)**2));}return clamp(y,120,WORLD_HEIGHT);}
function ensure(room){if(!room)return room;if(!Array.isArray(room.pickups))room.pickups=[];if(!Number.isInteger(room.lastPickupSpawnTurn))room.lastPickupSpawnTurn=0;for(const p of room.players){if(!Array.isArray(p.inventory))p.inventory=Array(INVENTORY_SIZE).fill(null);p.inventory=[...p.inventory.slice(0,INVENTORY_SIZE),...Array(INVENTORY_SIZE).fill(null)].slice(0,INVENTORY_SIZE);if(!Number.isInteger(p.selectedItemSlot)||p.selectedItemSlot<0||p.selectedItemSlot>INVENTORY_SIZE)p.selectedItemSlot=0;}return room;}
function resultFor(room){const alive=room.players.filter(p=>p.alive!==false);if(room.mode==='survival'){if(alive.length>1)return null;return{type:'survival',winnerPlayerId:alive[0]?.id??null,winnerName:alive[0]?.name??null,draw:alive.length===0};}const teams=[...new Set(alive.map(p=>p.team))];if(teams.length>1)return null;return{type:'team',winnerTeam:teams[0]??null,draw:teams.length===0};}
function spawn(room){ensure(room);if(room.pickups.length>=MAX_PICKUPS)return false;const candidates=[];for(let x=420;x<=WORLD_WIDTH-420;x+=55){const y=surface(room,x),l=surface(room,x-35),r=surface(room,x+35);if(y>=WORLD_HEIGHT-1||l>=WORLD_HEIGHT-1||r>=WORLD_HEIGHT-1||Math.abs(l-y)>95||Math.abs(r-y)>95)continue;if(room.players.some(p=>p.spawn&&p.alive!==false&&Math.hypot(p.spawn.x-x,p.spawn.y-(y-GROUND_OFFSET))<260))continue;if(room.pickups.some(p=>Math.abs(p.x-x)<260))continue;candidates.push({x,y:Math.round(y-24)});}if(!candidates.length)return false;const pt=candidates[randomInt(candidates.length)],turn=room.match?.turnNumber??0;room.pickups.push({id:`${room.code}-pickup-${turn}-${Date.now()}`,type:'heavy',label:'HEAVY BOMB',x:pt.x,y:pt.y,spawnTurn:turn,expiresAfterTurn:turn+PICKUP_LIFE});room.lastPickupSpawnTurn=turn;return true;}
function maintain(room){ensure(room);const turn=room.match?.turnNumber??0;room.pickups=room.pickups.filter(p=>turn<=p.expiresAfterTurn);if(room.status==='started'&&turn>=PICKUP_EVERY&&turn%PICKUP_EVERY===0&&room.lastPickupSpawnTurn!==turn)spawn(room);}
function collect(room,p){ensure(room);if(!p?.spawn||p.alive===false)return false;let changed=false;for(let i=room.pickups.length-1;i>=0;i--){const box=room.pickups[i];if(Math.hypot(p.spawn.x-box.x,(p.spawn.y-8)-box.y)>PICKUP_RADIUS)continue;const slot=p.inventory.findIndex(v=>v==null);if(slot<0)continue;p.inventory[slot]={type:box.type,label:box.label,pickedAtTurn:room.match?.turnNumber??0};if(p.selectedItemSlot===0)p.selectedItemSlot=slot+1;p.lastPickup={type:box.type,label:box.label,at:Date.now()};room.pickups.splice(i,1);changed=true;}return changed;}
function collectAll(room){for(const p of room.players)collect(room,p);}
function publicState(room){maintain(room);const s=basePublic(room);s.phase='6A';s.pickups=room.pickups.map(p=>({...p}));s.pickupRules={everyTurns:PICKUP_EVERY,lifetimeTurns:PICKUP_LIFE,inventorySize:INVENTORY_SIZE};s.players=s.players.map(pp=>{const p=room.players.find(x=>x.id===pp.id);return{...pp,inventory:p.inventory.map(i=>i?{...i}:null),selectedItemSlot:p.selectedItemSlot,lastPickup:p.lastPickup?{...p.lastPickup}:null};});if(s.match?.projectile)s.match.projectile={...s.match.projectile};return s;}
export const publicRoomState6A=publicState;
export function moveActivePlayer6A(id,d){const r=baseMove(id,d);if(r.ok)collect(r.room,r.room.players.find(p=>p.id===id));return r;}
export function jumpActivePlayer6A(id,d){const r=baseJump(id,d);if(r.ok)collect(r.room,r.room.players.find(p=>p.id===id));return r;}
export function selectItem6A(id,raw){const room=findRoomBySocket(id);if(!room)return{ok:false,error:'not_in_room'};ensure(room);const p=room.players.find(x=>x.id===id);if(!p||p.alive===false)return{ok:false,error:'player_missing'};const slot=Number(raw);if(!Number.isInteger(slot)||slot<0||slot>INVENTORY_SIZE)return{ok:false,error:'invalid_item_slot'};if(slot>0&&!p.inventory[slot-1])return{ok:false,error:'empty_item_slot'};p.selectedItemSlot=slot;return{ok:true,room};}
export function fireProjectile6A(id){const room=findRoomBySocket(id);if(!room)return{ok:false,error:'not_in_room'};ensure(room);const p=room.players.find(x=>x.id===id),slot=p?.selectedItemSlot??0,item=slot>0?p.inventory[slot-1]:null,r=baseFire(id);if(!r.ok)return r;if(r.room.match?.projectile)r.room.match.projectile.weaponType=item?.type==='heavy'?'heavy':'basic';if(item?.type==='heavy'){p.inventory[slot-1]=null;p.selectedItemSlot=0;}return r;}
function heavy(room,now){const q=room.match?.projectile;if(!q||q.weaponType!=='heavy'||!q.resolutionApplied||q.heavyResolutionApplied)return false;q.heavyResolutionApplied=true;if(!['terrain','player'].includes(q.impactReason))return true;for(const p of room.players){if(!p.spawn||p.alive===false)continue;const d=Math.hypot(p.spawn.x-q.impactX,(p.spawn.y-10)-q.impactY);if(d>HEAVY_RADIUS)continue;let target=Math.round(HEAVY_DAMAGE*(1-d/HEAVY_RADIUS));if(q.hitPlayerId===p.id)target=Math.max(target,HEAVY_DAMAGE);target=clamp(target,1,HEAVY_DAMAGE);const base=p.lastDamage?.sourcePlayerId===q.ownerPlayerId&&Math.abs((p.lastDamage?.at??0)-now)<1500?p.lastDamage.amount:0,bonus=Math.max(0,target-base);if(!bonus)continue;p.hp=Math.max(0,(p.hp??100)-bonus);p.lastDamage={amount:base+bonus,at:now,sourcePlayerId:q.ownerPlayerId};if(p.hp<=0)p.alive=false;}if(surface(room,q.impactX)<WORLD_HEIGHT-1)room.arena.craters.push({id:`${q.id}-heavy`,x:q.impactX,radius:HEAVY_CRATER_RADIUS,depth:HEAVY_CRATER_DEPTH,createdAt:now});room.match.pendingResult=resultFor(room);return true;}
export function advanceTurnIfDue6A(code,now=Date.now()){const r=baseAdvance(code,now);if(!r)return null;ensure(r);heavy(r,now);maintain(r);collectAll(r);return r;}
