import { randomInt } from 'node:crypto';
import { advanceTurnIfDue as baseAdvance, fireProjectile as baseFire, findRoomBySocket, getRoom, jumpActivePlayer as baseJump, moveActivePlayer as baseMove, publicRoomState as basePublic } from './rooms.js';

const WORLD_WIDTH=5000,WORLD_HEIGHT=5000,GROUND_OFFSET=8,INVENTORY_SIZE=2,PICKUP_EVERY=3,PICKUP_LIFE=4,PICKUP_RADIUS=64,MAX_PICKUPS=2;
const BASIC_RADIUS=260,HEAVY_DAMAGE=60,HEAVY_RADIUS=320,HEAVY_CRATER_RADIUS=190,HEAVY_CRATER_DEPTH=90;
const TRIPLE_DAMAGE=20,TRIPLE_RADIUS=175,TRIPLE_CRATER_RADIUS=78,TRIPLE_CRATER_DEPTH=78,TRIPLE_SPREAD=6;
const CLUSTER_DAMAGE=14,CLUSTER_RADIUS=150,CLUSTER_CRATER_RADIUS=70,CLUSTER_CRATER_DEPTH=70;
const SHIELD_FACTOR=.5,SHIELD_ACTION_MS=1200,PROJECTILE_GRAVITY=480,PROJECTILE_DT=.02,PROJECTILE_MAX_SECONDS=8,HIT_RADIUS=26;
const ITEM_POOL=[
  {type:'heavy',label:'HEAVY BOMB',weight:30},
  {type:'triple',label:'TRIPLE SHOT',weight:30},
  {type:'cluster',label:'CLUSTER BOMB',weight:25},
  {type:'shield',label:'SHIELD',weight:15}
];
const HOLES={rolling:[],terraces:[[2430,2550]],twinpeaks:[[2390,2510]],basin:[[1140,1240],[3760,3860]],brokenridge:[[1010,1140],[2410,2550],[3860,3980]],islands:[[900,1040],[1920,2080],[2910,3070],[3960,4110]],canyon:[[2380,2580]]};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const gaussian=(x,c,w,a)=>a*Math.exp(-((x-c)**2)/w);
const plateau=(x,l,r,y,f)=>x>=l&&x<=r?y:f;
function baseY(p,x){switch(p){case'terraces':{let y=3520+Math.sin(x/560)*100;y=plateau(x,330,900,3190,y);y=plateau(x,1040,1640,2920,y);y=plateau(x,1770,2350,3250,y);y=plateau(x,2630,3260,2820,y);y=plateau(x,3390,3970,3110,y);return plateau(x,4110,4680,2870,y);}case'twinpeaks':{let y=3650-gaussian(x,1200,260000,850)-gaussian(x,3820,300000,900)+Math.sin(x/280)*60;if(x>650&&x<980)y=3000;if(x>1510&&x<1850)y=3170;if(x>3150&&x<3460)y=3090;if(x>4050&&x<4410)y=2890;return y;}case'basin':{let y=2870+gaussian(x,2500,850000,690)+Math.sin(x/410)*65;if(x>420&&x<950)y=2750;if(x>1320&&x<1760)y=3160;if(x>3240&&x<3680)y=3160;if(x>4050&&x<4580)y=2750;return y;}case'brokenridge':{let y=3490+Math.sin(x/210)*170+Math.sin(x/690+1.1)*130;if(x>420&&x<900)y=3070;if(x>1260&&x<1720)y=2740;if(x>1900&&x<2320)y=3260;if(x>2700&&x<3160)y=2860;if(x>3330&&x<3770)y=3180;if(x>4140&&x<4620)y=2780;return y;}case'islands':if(x<900)return 3100-gaussian(x,520,90000,260);if(x<1920)return 2840-gaussian(x,1470,125000,190);if(x<2910)return 3260-gaussian(x,2480,130000,320);if(x<3960)return 2760-gaussian(x,3470,135000,220);return 3160-gaussian(x,4540,100000,280);case'canyon':{let y=2920+Math.min(Math.abs(x-2500)*.28,700);if(x>420&&x<980)y=2700;if(x>1120&&x<1640)y=3030;if(x>1800&&x<2260)y=3380;if(x>2740&&x<3200)y=3380;if(x>3360&&x<3880)y=3030;if(x>4020&&x<4580)y=2700;return y;}default:{let y=3440+Math.sin(x/470)*165+Math.sin(x/980+.7)*95;if(x>700&&x<1120)y=3140;if(x>1760&&x<2140)y=2920;if(x>2840&&x<3240)y=3170;if(x>3890&&x<4320)y=2860;return y;}}}
function surface(room,x){const px=clamp(x,0,WORLD_WIDTH),p=room.terrainPreset||'rolling';if((HOLES[p]||[]).some(([l,r])=>px>=l&&px<=r))return WORLD_HEIGHT;let y=baseY(p,px);for(const c of room.arena?.craters||[]){const dx=Math.abs(px-c.x);if(dx<c.radius)y+=c.depth*Math.sqrt(Math.max(0,1-(dx/c.radius)**2));}return clamp(y,120,WORLD_HEIGHT);}
function ensure(room){if(!room)return room;if(!Array.isArray(room.pickups))room.pickups=[];if(!Number.isInteger(room.lastPickupSpawnTurn))room.lastPickupSpawnTurn=0;if(room.match&&!('specialAction'in room.match))room.match.specialAction=null;for(const p of room.players){if(!Array.isArray(p.inventory))p.inventory=Array(INVENTORY_SIZE).fill(null);p.inventory=[...p.inventory.slice(0,INVENTORY_SIZE),...Array(INVENTORY_SIZE).fill(null)].slice(0,INVENTORY_SIZE);if(!Number.isInteger(p.selectedItemSlot)||p.selectedItemSlot<1||p.selectedItemSlot>INVENTORY_SIZE+1)p.selectedItemSlot=1;if(!('shield'in p))p.shield=null;}return room;}
function resultFor(room){const alive=room.players.filter(p=>p.alive!==false);if(room.mode==='survival'){if(alive.length>1)return null;return{type:'survival',winnerPlayerId:alive[0]?.id??null,winnerName:alive[0]?.name??null,draw:alive.length===0};}const teams=[...new Set(alive.map(p=>p.team))];if(teams.length>1)return null;return{type:'team',winnerTeam:teams[0]??null,draw:teams.length===0};}
function randomItem(){const total=ITEM_POOL.reduce((s,i)=>s+i.weight,0);let roll=randomInt(total);for(const item of ITEM_POOL){if(roll<item.weight)return item;roll-=item.weight;}return ITEM_POOL[0];}
function spawn(room){ensure(room);if(room.pickups.length>=MAX_PICKUPS)return false;const candidates=[];for(let x=140;x<=WORLD_WIDTH-140;x+=45){const y=surface(room,x);if(y>=WORLD_HEIGHT-1)continue;if(room.players.some(p=>p.spawn&&p.alive!==false&&Math.hypot(p.spawn.x-x,p.spawn.y-(y-GROUND_OFFSET))<90))continue;if(room.pickups.some(p=>Math.abs(p.x-x)<140))continue;candidates.push({x,y:Math.round(y-24)});}if(!candidates.length)return false;const pt=candidates[randomInt(candidates.length)],turn=room.match?.turnNumber??0,item=randomItem();room.pickups.push({id:`${room.code}-pickup-${turn}-${Date.now()}`,type:item.type,label:item.label,x:pt.x,y:pt.y,spawnTurn:turn,expiresAfterTurn:turn+PICKUP_LIFE});room.lastPickupSpawnTurn=turn;return true;}
function maintain(room){ensure(room);const turn=room.match?.turnNumber??0;room.pickups=room.pickups.filter(p=>turn<=p.expiresAfterTurn);if(room.status==='started'&&turn>=PICKUP_EVERY&&turn%PICKUP_EVERY===0&&room.lastPickupSpawnTurn!==turn)spawn(room);}
function givePickup(room,p,box,method='touch'){const slot=p.inventory.findIndex(v=>v==null);if(slot<0)return false;p.inventory[slot]={type:box.type,label:box.label,pickedAtTurn:room.match?.turnNumber??0};p.lastPickup={type:box.type,label:box.label,method,at:Date.now()};return true;}
function collect(room,p){ensure(room);if(!p?.spawn||p.alive===false)return false;let changed=false;for(let i=room.pickups.length-1;i>=0;i--){const box=room.pickups[i];if(Math.hypot(p.spawn.x-box.x,(p.spawn.y-8)-box.y)>PICKUP_RADIUS)continue;if(!givePickup(room,p,box,'touch'))continue;room.pickups.splice(i,1);changed=true;}return changed;}
function collectAll(room){for(const p of room.players)collect(room,p);}
function collectAt(room,ownerId,x,y,radius,method='explosion'){const shooter=room.players.find(p=>p.id===ownerId);if(!shooter)return false;let changed=false;for(let i=room.pickups.length-1;i>=0;i--){const box=room.pickups[i];if(Math.hypot(box.x-x,box.y-y)>radius)continue;if(!givePickup(room,shooter,box,method))continue;room.pickups.splice(i,1);changed=true;}return changed;}
function publicState(room){maintain(room);const s=basePublic(room);s.phase='6B';s.pickups=room.pickups.map(p=>({...p}));s.pickupRules={everyTurns:PICKUP_EVERY,lifetimeTurns:PICKUP_LIFE,inventorySize:INVENTORY_SIZE,totalWeaponSlots:INVENTORY_SIZE+1,collectByTouch:true,collectByExplosion:true};s.itemPool=ITEM_POOL.map(({type,label,weight})=>({type,label,weight}));s.players=s.players.map(pp=>{const p=room.players.find(x=>x.id===pp.id);return{...pp,inventory:p.inventory.map(i=>i?{...i}:null),selectedItemSlot:p.selectedItemSlot,lastPickup:p.lastPickup?{...p.lastPickup}:null,shield:p.shield?{...p.shield}:null};});if(s.match?.projectile)s.match.projectile={...s.match.projectile,volley:s.match.projectile.volley?.map(v=>({...v})),clusterImpacts:s.match.projectile.clusterImpacts?.map(v=>({...v}))};if(s.match?.specialAction)s.match.specialAction={...s.match.specialAction};return s;}
export const publicRoomState6A=publicState;
export function moveActivePlayer6A(id,d){const r=baseMove(id,d);if(r.ok)collect(r.room,r.room.players.find(p=>p.id===id));return r;}
export function jumpActivePlayer6A(id,d){const r=baseJump(id,d);if(r.ok)collect(r.room,r.room.players.find(p=>p.id===id));return r;}
export function selectItem6A(id,raw){const room=findRoomBySocket(id);if(!room)return{ok:false,error:'not_in_room'};ensure(room);const p=room.players.find(x=>x.id===id);if(!p||p.alive===false)return{ok:false,error:'player_missing'};const slot=Number(raw);if(!Number.isInteger(slot)||slot<1||slot>INVENTORY_SIZE+1)return{ok:false,error:'invalid_item_slot'};if(slot>1&&!p.inventory[slot-2])return{ok:false,error:'empty_item_slot'};p.selectedItemSlot=slot;return{ok:true,room};}
function validateSpecial(room,p,id){if(!room)return'not_in_room';if(room.status!=='started')return'match_not_started';if(room.match?.activePlayerId!==id)return'not_your_turn';if(room.match?.projectile||room.match?.specialAction)return'shot_in_flight';if(!p?.spawn||p.alive===false)return'player_missing';if(p.motion?.endsAt&&Date.now()<p.motion.endsAt)return'player_in_motion';return null;}
function simulate(room,p,angle,power,now){const facing=p.spawn.facing||1,rad=angle*Math.PI/180,speed=320+power*9,startX=p.spawn.x+facing*24,startY=p.spawn.y-24,vx=Math.cos(rad)*speed*facing,vy=-Math.sin(rad)*speed,windAccel=(room.match?.wind?.signed??0)*1.5;let impactX=startX,impactY=startY,impactT=PROJECTILE_MAX_SECONDS,reason='timeout',hitPlayerId=null;for(let t=PROJECTILE_DT;t<=PROJECTILE_MAX_SECONDS;t+=PROJECTILE_DT){const x=startX+vx*t+.5*windAccel*t*t,y=startY+vy*t+.5*PROJECTILE_GRAVITY*t*t;impactX=x;impactY=y;impactT=t;if(x<0||x>WORLD_WIDTH||y>WORLD_HEIGHT){reason='out_of_bounds';break;}for(const target of room.players){if(target.alive===false||!target.spawn||(target.id===p.id&&t<.14))continue;if(Math.hypot(x-target.spawn.x,y-(target.spawn.y-10))<=HIT_RADIUS){reason='player';hitPlayerId=target.id;break;}}if(hitPlayerId)break;const ground=surface(room,x);if(ground<WORLD_HEIGHT&&t>.08&&y>=ground){impactY=ground;reason='terrain';break;}}const durationMs=Math.max(220,Math.round(impactT*1000));return{id:`${room.code}-${room.match.turnNumber}-${now}-${angle}`,ownerPlayerId:p.id,startedAt:now,impactAt:now+durationMs,durationMs,startX,startY,vx,vy,gravity:PROJECTILE_GRAVITY,windAccel,impactX:clamp(impactX,0,WORLD_WIDTH),impactY,impactReason:reason,hitPlayerId,angle,power};}
function consumeSelected(p){const slot=p.selectedItemSlot??1,item=slot>1?p.inventory[slot-2]:null;if(item){p.inventory[slot-2]=null;p.selectedItemSlot=1;}return item;}
export function fireProjectile6A(id){const room=findRoomBySocket(id);if(!room)return{ok:false,error:'not_in_room'};ensure(room);const p=room.players.find(x=>x.id===id),slot=p?.selectedItemSlot??1,item=slot>1?p.inventory[slot-2]:null;
  if(item?.type==='shield'){const error=validateSpecial(room,p,id);if(error)return{ok:false,error};consumeSelected(p);const now=Date.now();p.shield={factor:SHIELD_FACTOR,activatedAt:now,activatedTurn:room.match?.turnNumber??0};room.match.specialAction={type:'shield',label:'SHIELD ACTIVATED',ownerPlayerId:id,startedAt:now,endsAt:now+SHIELD_ACTION_MS};room.match.turnEndsAt=now+SHIELD_ACTION_MS;room.camera={mode:'follow',targetPlayerId:id};return{ok:true,room};}
  const r=baseFire(id);if(!r.ok)return r;const q=r.room.match?.projectile,chosen=item?.type??'basic';if(q){q.weaponType=chosen;q.preImpactHp=Object.fromEntries(r.room.players.map(x=>[x.id,x.hp??100]));q.preImpactAlive=Object.fromEntries(r.room.players.map(x=>[x.id,x.alive!==false]));q.preImpactSpawns=Object.fromEntries(r.room.players.map(x=>[x.id,x.spawn?{...x.spawn}:null]));if(chosen==='triple'){const a=r.room.match.aimAngle,power=r.room.match.aimPower;q.volley=[simulate(r.room,p,a-TRIPLE_SPREAD,power,q.startedAt),{...q},simulate(r.room,p,a+TRIPLE_SPREAD,power,q.startedAt)];q.specialResolveAt=Math.max(...q.volley.map(v=>v.impactAt));q.resolveAt=q.specialResolveAt+900;r.room.match.turnEndsAt=q.resolveAt;}else if(chosen==='cluster'){const offsets=[-180,-90,0,90,180];q.clusterImpacts=offsets.map((dx,index)=>{const x=clamp(q.impactX+dx,30,WORLD_WIDTH-30);return{x,y:surface(r.room,x),impactAt:q.impactAt+320+index*85,index};});q.specialResolveAt=Math.max(...q.clusterImpacts.map(v=>v.impactAt));q.resolveAt=q.specialResolveAt+900;r.room.match.turnEndsAt=q.resolveAt;}}
  if(item)consumeSelected(p);return r;}
function restoreBaseForSpecial(room,q,now){if(!q||q.baseNeutralized||!['triple','cluster'].includes(q.weaponType)||!q.resolutionApplied)return false;q.baseNeutralized=true;room.arena.craters=room.arena.craters.filter(c=>c.id!==q.id);for(const p of room.players){const preHp=q.preImpactHp?.[p.id],preAlive=q.preImpactAlive?.[p.id];if(preHp==null)continue;if(p.motion?.type==='knockbackVoid')continue;p.hp=preHp;p.alive=preAlive;if(p.lastDamage?.sourcePlayerId===q.ownerPlayerId&&Math.abs((p.lastDamage.at??0)-now)<1800)p.lastDamage=null;}room.match.pendingResult=resultFor(room);return true;}
function applyDamage(room,q,x,y,maxDamage,radius,craterRadius,craterDepth,tag){for(const p of room.players){if(p.alive===false||!p.spawn)continue;const ref=q.preImpactSpawns?.[p.id]??p.spawn,d=Math.hypot(ref.x-x,(ref.y-10)-y);if(d>radius)continue;let damage=Math.round(maxDamage*(1-d/radius));if(damage<1)damage=1;if(p.shield){damage=Math.max(1,Math.ceil(damage*p.shield.factor));p.shield=null;}p.hp=Math.max(0,(p.hp??100)-damage);p.lastDamage={amount:damage,at:Date.now(),sourcePlayerId:q.ownerPlayerId};if(p.hp<=0)p.alive=false;}if(surface(room,x)<WORLD_HEIGHT-1)room.arena.craters.push({id:`${q.id}-${tag}`,x,radius:craterRadius,depth:craterDepth,createdAt:Date.now()});collectAt(room,q.ownerPlayerId,x,y,radius,'explosion');}
function resolveTriple(room,q,now){if(q.specialResolutionApplied||now<(q.specialResolveAt??0))return false;q.specialResolutionApplied=true;for(const [index,v] of (q.volley??[]).entries()){if(!['terrain','player'].includes(v.impactReason))continue;applyDamage(room,q,v.impactX,v.impactY,TRIPLE_DAMAGE,TRIPLE_RADIUS,TRIPLE_CRATER_RADIUS,TRIPLE_CRATER_DEPTH,`triple-${index}`);}room.match.pendingResult=resultFor(room);return true;}
function resolveCluster(room,q,now){if(q.specialResolutionApplied||now<(q.specialResolveAt??0))return false;q.specialResolutionApplied=true;for(const v of q.clusterImpacts??[]){if(v.y>=WORLD_HEIGHT-1)continue;applyDamage(room,q,v.x,v.y,CLUSTER_DAMAGE,CLUSTER_RADIUS,CLUSTER_CRATER_RADIUS,CLUSTER_CRATER_DEPTH,`cluster-${v.index}`);}room.match.pendingResult=resultFor(room);return true;}
function heavy(room,now){const q=room.match?.projectile;if(!q||q.weaponType!=='heavy'||!q.resolutionApplied||q.heavyResolutionApplied)return false;q.heavyResolutionApplied=true;if(!['terrain','player'].includes(q.impactReason))return true;for(const p of room.players){if(!p.spawn||p.alive===false)continue;const d=Math.hypot(p.spawn.x-q.impactX,(p.spawn.y-10)-q.impactY);if(d>HEAVY_RADIUS)continue;let target=Math.round(HEAVY_DAMAGE*(1-d/HEAVY_RADIUS));if(q.hitPlayerId===p.id)target=Math.max(target,HEAVY_DAMAGE);target=clamp(target,1,HEAVY_DAMAGE);const base=p.lastDamage?.sourcePlayerId===q.ownerPlayerId&&Math.abs((p.lastDamage?.at??0)-now)<1500?p.lastDamage.amount:0,bonus=Math.max(0,target-base);if(!bonus)continue;p.hp=Math.max(0,(p.hp??100)-bonus);p.lastDamage={amount:base+bonus,at:now,sourcePlayerId:q.ownerPlayerId};if(p.hp<=0)p.alive=false;}if(surface(room,q.impactX)<WORLD_HEIGHT-1)room.arena.craters.push({id:`${q.id}-heavy`,x:q.impactX,radius:HEAVY_CRATER_RADIUS,depth:HEAVY_CRATER_DEPTH,createdAt:now});collectAt(room,q.ownerPlayerId,q.impactX,q.impactY,HEAVY_RADIUS,'explosion');room.match.pendingResult=resultFor(room);return true;}
function mitigateShieldAfterBase(room,q,now){if(!q?.resolutionApplied||q.shieldMitigationApplied||['triple','cluster'].includes(q.weaponType))return false;q.shieldMitigationApplied=true;for(const p of room.players){if(!p.shield||!p.lastDamage||p.lastDamage.sourcePlayerId!==q.ownerPlayerId||Math.abs((p.lastDamage.at??0)-now)>1800)continue;if(p.motion?.type==='knockbackVoid'){p.shield=null;continue;}const original=p.lastDamage.amount,reduced=Math.max(1,Math.ceil(original*p.shield.factor)),restore=original-reduced;p.hp=Math.min(100,(p.hp??0)+restore);p.lastDamage={...p.lastDamage,amount:reduced};p.shield=null;if(p.hp>0)p.alive=true;}room.match.pendingResult=resultFor(room);return true;}
export function advanceTurnIfDue6A(code,now=Date.now()){const existing=getRoom(code);if(!existing)return null;ensure(existing);if(existing.match?.specialAction){if(now<existing.match.specialAction.endsAt)return null;existing.match.specialAction=null;}const pending=existing.match?.projectile;if(pending&&['triple','cluster'].includes(pending.weaponType)&&!pending.specialResolutionApplied&&now>=(pending.specialResolveAt??0)){if(pending.weaponType==='triple')resolveTriple(existing,pending,now);else resolveCluster(existing,pending,now);maintain(existing);collectAll(existing);return existing;}const r=baseAdvance(code,now);if(!r)return null;ensure(r);const q=r.match?.projectile;if(q?.resolutionApplied){restoreBaseForSpecial(r,q,now);if(q.weaponType==='triple'&&now>=(q.specialResolveAt??0))resolveTriple(r,q,now);else if(q.weaponType==='cluster'&&now>=(q.specialResolveAt??0))resolveCluster(r,q,now);else if(!['triple','cluster'].includes(q.weaponType)){heavy(r,now);if(q.weaponType==='basic')collectAt(r,q.ownerPlayerId,q.impactX,q.impactY,BASIC_RADIUS,'explosion');mitigateShieldAfterBase(r,q,now);}}maintain(r);collectAll(r);return r;}
