export const CLIENT_EVENTS = Object.freeze({
  CREATE_ROOM: 'CREATE_ROOM',
  JOIN_ROOM: 'JOIN_ROOM',
  READY: 'READY',
  CHANGE_TEAM: 'CHANGE_TEAM',
  AIM: 'AIM',
  SET_POWER: 'SET_POWER',
  SHOOT: 'SHOOT',
  PING: 'PING'
});

export const SERVER_EVENTS = Object.freeze({
  ROOM_STATE: 'ROOM_STATE',
  PLAYER_JOINED: 'PLAYER_JOINED',
  PLAYER_LEFT: 'PLAYER_LEFT',
  GAME_STARTED: 'GAME_STARTED',
  TURN_STARTED: 'TURN_STARTED',
  WIND_UPDATE: 'WIND_UPDATE',
  SHOT_RESULT: 'SHOT_RESULT',
  PLAYER_DAMAGED: 'PLAYER_DAMAGED',
  PLAYER_DIED: 'PLAYER_DIED',
  TERRAIN_UPDATED: 'TERRAIN_UPDATED',
  GAME_OVER: 'GAME_OVER',
  ERROR: 'ERROR'
});
